// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: shared/packets.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Packet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Packet_ErrorRes
	//	*Packet_LoginReq
	//	*Packet_LoginRes
	//	*Packet_RegisterReq
	//	*Packet_RegisterRes
	//	*Packet_MyCharactersListReq
	//	*Packet_MyCharactersListRes
	//	*Packet_CharacterJoinReq
	//	*Packet_CharacterJoinRes
	//	*Packet_CastSpellReq
	//	*Packet_CastSpellRes
	Payload       isPacket_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_shared_packets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Packet) GetPayload() isPacket_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Packet) GetErrorRes() *ErrorRes {
	if x != nil {
		if x, ok := x.Payload.(*Packet_ErrorRes); ok {
			return x.ErrorRes
		}
	}
	return nil
}

func (x *Packet) GetLoginReq() *LoginReq {
	if x != nil {
		if x, ok := x.Payload.(*Packet_LoginReq); ok {
			return x.LoginReq
		}
	}
	return nil
}

func (x *Packet) GetLoginRes() *LoginRes {
	if x != nil {
		if x, ok := x.Payload.(*Packet_LoginRes); ok {
			return x.LoginRes
		}
	}
	return nil
}

func (x *Packet) GetRegisterReq() *RegisterReq {
	if x != nil {
		if x, ok := x.Payload.(*Packet_RegisterReq); ok {
			return x.RegisterReq
		}
	}
	return nil
}

func (x *Packet) GetRegisterRes() *RegisterRes {
	if x != nil {
		if x, ok := x.Payload.(*Packet_RegisterRes); ok {
			return x.RegisterRes
		}
	}
	return nil
}

func (x *Packet) GetMyCharactersListReq() *MyCharactersListReq {
	if x != nil {
		if x, ok := x.Payload.(*Packet_MyCharactersListReq); ok {
			return x.MyCharactersListReq
		}
	}
	return nil
}

func (x *Packet) GetMyCharactersListRes() *MyCharactersListRes {
	if x != nil {
		if x, ok := x.Payload.(*Packet_MyCharactersListRes); ok {
			return x.MyCharactersListRes
		}
	}
	return nil
}

func (x *Packet) GetCharacterJoinReq() *CharacterJoinReq {
	if x != nil {
		if x, ok := x.Payload.(*Packet_CharacterJoinReq); ok {
			return x.CharacterJoinReq
		}
	}
	return nil
}

func (x *Packet) GetCharacterJoinRes() *CharacterJoinRes {
	if x != nil {
		if x, ok := x.Payload.(*Packet_CharacterJoinRes); ok {
			return x.CharacterJoinRes
		}
	}
	return nil
}

func (x *Packet) GetCastSpellReq() *CastSpellReq {
	if x != nil {
		if x, ok := x.Payload.(*Packet_CastSpellReq); ok {
			return x.CastSpellReq
		}
	}
	return nil
}

func (x *Packet) GetCastSpellRes() *CastSpellRes {
	if x != nil {
		if x, ok := x.Payload.(*Packet_CastSpellRes); ok {
			return x.CastSpellRes
		}
	}
	return nil
}

type isPacket_Payload interface {
	isPacket_Payload()
}

type Packet_ErrorRes struct {
	ErrorRes *ErrorRes `protobuf:"bytes,2,opt,name=error_res,json=errorRes,proto3,oneof"`
}

type Packet_LoginReq struct {
	LoginReq *LoginReq `protobuf:"bytes,3,opt,name=login_req,json=loginReq,proto3,oneof"`
}

type Packet_LoginRes struct {
	LoginRes *LoginRes `protobuf:"bytes,4,opt,name=login_res,json=loginRes,proto3,oneof"`
}

type Packet_RegisterReq struct {
	RegisterReq *RegisterReq `protobuf:"bytes,5,opt,name=register_req,json=registerReq,proto3,oneof"`
}

type Packet_RegisterRes struct {
	RegisterRes *RegisterRes `protobuf:"bytes,6,opt,name=register_res,json=registerRes,proto3,oneof"`
}

type Packet_MyCharactersListReq struct {
	MyCharactersListReq *MyCharactersListReq `protobuf:"bytes,7,opt,name=my_characters_list_req,json=myCharactersListReq,proto3,oneof"`
}

type Packet_MyCharactersListRes struct {
	MyCharactersListRes *MyCharactersListRes `protobuf:"bytes,8,opt,name=my_characters_list_res,json=myCharactersListRes,proto3,oneof"`
}

type Packet_CharacterJoinReq struct {
	CharacterJoinReq *CharacterJoinReq `protobuf:"bytes,9,opt,name=character_join_req,json=characterJoinReq,proto3,oneof"`
}

type Packet_CharacterJoinRes struct {
	CharacterJoinRes *CharacterJoinRes `protobuf:"bytes,10,opt,name=character_join_res,json=characterJoinRes,proto3,oneof"`
}

type Packet_CastSpellReq struct {
	CastSpellReq *CastSpellReq `protobuf:"bytes,11,opt,name=cast_spell_req,json=castSpellReq,proto3,oneof"`
}

type Packet_CastSpellRes struct {
	CastSpellRes *CastSpellRes `protobuf:"bytes,12,opt,name=cast_spell_res,json=castSpellRes,proto3,oneof"`
}

func (*Packet_ErrorRes) isPacket_Payload() {}

func (*Packet_LoginReq) isPacket_Payload() {}

func (*Packet_LoginRes) isPacket_Payload() {}

func (*Packet_RegisterReq) isPacket_Payload() {}

func (*Packet_RegisterRes) isPacket_Payload() {}

func (*Packet_MyCharactersListReq) isPacket_Payload() {}

func (*Packet_MyCharactersListRes) isPacket_Payload() {}

func (*Packet_CharacterJoinReq) isPacket_Payload() {}

func (*Packet_CharacterJoinRes) isPacket_Payload() {}

func (*Packet_CastSpellReq) isPacket_Payload() {}

func (*Packet_CastSpellRes) isPacket_Payload() {}

type ErrorRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorRes) Reset() {
	*x = ErrorRes{}
	mi := &file_shared_packets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorRes) ProtoMessage() {}

func (x *ErrorRes) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorRes.ProtoReflect.Descriptor instead.
func (*ErrorRes) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_shared_packets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{2}
}

func (x *LoginReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRes) Reset() {
	*x = LoginRes{}
	mi := &file_shared_packets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRes) ProtoMessage() {}

func (x *LoginRes) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRes.ProtoReflect.Descriptor instead.
func (*LoginRes) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{3}
}

type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_shared_packets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRes) Reset() {
	*x = RegisterRes{}
	mi := &file_shared_packets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRes) ProtoMessage() {}

func (x *RegisterRes) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRes.ProtoReflect.Descriptor instead.
func (*RegisterRes) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{5}
}

type MyCharactersListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyCharactersListReq) Reset() {
	*x = MyCharactersListReq{}
	mi := &file_shared_packets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyCharactersListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyCharactersListReq) ProtoMessage() {}

func (x *MyCharactersListReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyCharactersListReq.ProtoReflect.Descriptor instead.
func (*MyCharactersListReq) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{6}
}

type MyCharacter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Level         uint32                 `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyCharacter) Reset() {
	*x = MyCharacter{}
	mi := &file_shared_packets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyCharacter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyCharacter) ProtoMessage() {}

func (x *MyCharacter) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyCharacter.ProtoReflect.Descriptor instead.
func (*MyCharacter) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{7}
}

func (x *MyCharacter) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MyCharacter) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *MyCharacter) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type MyCharactersListRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Characters    []*MyCharacter         `protobuf:"bytes,1,rep,name=characters,proto3" json:"characters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyCharactersListRes) Reset() {
	*x = MyCharactersListRes{}
	mi := &file_shared_packets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyCharactersListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyCharactersListRes) ProtoMessage() {}

func (x *MyCharactersListRes) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyCharactersListRes.ProtoReflect.Descriptor instead.
func (*MyCharactersListRes) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{8}
}

func (x *MyCharactersListRes) GetCharacters() []*MyCharacter {
	if x != nil {
		return x.Characters
	}
	return nil
}

type CharacterJoinReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterJoinReq) Reset() {
	*x = CharacterJoinReq{}
	mi := &file_shared_packets_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterJoinReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterJoinReq) ProtoMessage() {}

func (x *CharacterJoinReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterJoinReq.ProtoReflect.Descriptor instead.
func (*CharacterJoinReq) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{9}
}

func (x *CharacterJoinReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CharacterJoinRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterJoinRes) Reset() {
	*x = CharacterJoinRes{}
	mi := &file_shared_packets_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterJoinRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterJoinRes) ProtoMessage() {}

func (x *CharacterJoinRes) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterJoinRes.ProtoReflect.Descriptor instead.
func (*CharacterJoinRes) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{10}
}

type CastSpellReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpellId       uint32                 `protobuf:"varint,1,opt,name=spell_id,json=spellId,proto3" json:"spell_id,omitempty"`
	TargetId      uint32                 `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CastSpellReq) Reset() {
	*x = CastSpellReq{}
	mi := &file_shared_packets_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CastSpellReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastSpellReq) ProtoMessage() {}

func (x *CastSpellReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastSpellReq.ProtoReflect.Descriptor instead.
func (*CastSpellReq) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{11}
}

func (x *CastSpellReq) GetSpellId() uint32 {
	if x != nil {
		return x.SpellId
	}
	return 0
}

func (x *CastSpellReq) GetTargetId() uint32 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

type CastSpellRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CastSpellRes) Reset() {
	*x = CastSpellRes{}
	mi := &file_shared_packets_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CastSpellRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastSpellRes) ProtoMessage() {}

func (x *CastSpellRes) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastSpellRes.ProtoReflect.Descriptor instead.
func (*CastSpellRes) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{12}
}

var File_shared_packets_proto protoreflect.FileDescriptor

const file_shared_packets_proto_rawDesc = "" +
	"\n" +
	"\x14shared/packets.proto\"\x95\x05\n" +
	"\x06Packet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12(\n" +
	"\terror_res\x18\x02 \x01(\v2\t.ErrorResH\x00R\berrorRes\x12(\n" +
	"\tlogin_req\x18\x03 \x01(\v2\t.LoginReqH\x00R\bloginReq\x12(\n" +
	"\tlogin_res\x18\x04 \x01(\v2\t.LoginResH\x00R\bloginRes\x121\n" +
	"\fregister_req\x18\x05 \x01(\v2\f.RegisterReqH\x00R\vregisterReq\x121\n" +
	"\fregister_res\x18\x06 \x01(\v2\f.RegisterResH\x00R\vregisterRes\x12K\n" +
	"\x16my_characters_list_req\x18\a \x01(\v2\x14.MyCharactersListReqH\x00R\x13myCharactersListReq\x12K\n" +
	"\x16my_characters_list_res\x18\b \x01(\v2\x14.MyCharactersListResH\x00R\x13myCharactersListRes\x12A\n" +
	"\x12character_join_req\x18\t \x01(\v2\x11.CharacterJoinReqH\x00R\x10characterJoinReq\x12A\n" +
	"\x12character_join_res\x18\n" +
	" \x01(\v2\x11.CharacterJoinResH\x00R\x10characterJoinRes\x125\n" +
	"\x0ecast_spell_req\x18\v \x01(\v2\r.CastSpellReqH\x00R\fcastSpellReq\x125\n" +
	"\x0ecast_spell_res\x18\f \x01(\v2\r.CastSpellResH\x00R\fcastSpellResB\t\n" +
	"\apayload\"\x1c\n" +
	"\bErrorRes\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"B\n" +
	"\bLoginReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\n" +
	"\n" +
	"\bLoginRes\"E\n" +
	"\vRegisterReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\r\n" +
	"\vRegisterRes\"\x15\n" +
	"\x13MyCharactersListReq\"O\n" +
	"\vMyCharacter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x14\n" +
	"\x05level\x18\x03 \x01(\rR\x05level\"C\n" +
	"\x13MyCharactersListRes\x12,\n" +
	"\n" +
	"characters\x18\x01 \x03(\v2\f.MyCharacterR\n" +
	"characters\"\"\n" +
	"\x10CharacterJoinReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x12\n" +
	"\x10CharacterJoinRes\"F\n" +
	"\fCastSpellReq\x12\x19\n" +
	"\bspell_id\x18\x01 \x01(\rR\aspellId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\rR\btargetId\"\x0e\n" +
	"\fCastSpellResB&Z$server/pkg/network/protocol;protocolb\x06proto3"

var (
	file_shared_packets_proto_rawDescOnce sync.Once
	file_shared_packets_proto_rawDescData []byte
)

func file_shared_packets_proto_rawDescGZIP() []byte {
	file_shared_packets_proto_rawDescOnce.Do(func() {
		file_shared_packets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_packets_proto_rawDesc), len(file_shared_packets_proto_rawDesc)))
	})
	return file_shared_packets_proto_rawDescData
}

var file_shared_packets_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_shared_packets_proto_goTypes = []any{
	(*Packet)(nil),              // 0: Packet
	(*ErrorRes)(nil),            // 1: ErrorRes
	(*LoginReq)(nil),            // 2: LoginReq
	(*LoginRes)(nil),            // 3: LoginRes
	(*RegisterReq)(nil),         // 4: RegisterReq
	(*RegisterRes)(nil),         // 5: RegisterRes
	(*MyCharactersListReq)(nil), // 6: MyCharactersListReq
	(*MyCharacter)(nil),         // 7: MyCharacter
	(*MyCharactersListRes)(nil), // 8: MyCharactersListRes
	(*CharacterJoinReq)(nil),    // 9: CharacterJoinReq
	(*CharacterJoinRes)(nil),    // 10: CharacterJoinRes
	(*CastSpellReq)(nil),        // 11: CastSpellReq
	(*CastSpellRes)(nil),        // 12: CastSpellRes
}
var file_shared_packets_proto_depIdxs = []int32{
	1,  // 0: Packet.error_res:type_name -> ErrorRes
	2,  // 1: Packet.login_req:type_name -> LoginReq
	3,  // 2: Packet.login_res:type_name -> LoginRes
	4,  // 3: Packet.register_req:type_name -> RegisterReq
	5,  // 4: Packet.register_res:type_name -> RegisterRes
	6,  // 5: Packet.my_characters_list_req:type_name -> MyCharactersListReq
	8,  // 6: Packet.my_characters_list_res:type_name -> MyCharactersListRes
	9,  // 7: Packet.character_join_req:type_name -> CharacterJoinReq
	10, // 8: Packet.character_join_res:type_name -> CharacterJoinRes
	11, // 9: Packet.cast_spell_req:type_name -> CastSpellReq
	12, // 10: Packet.cast_spell_res:type_name -> CastSpellRes
	7,  // 11: MyCharactersListRes.characters:type_name -> MyCharacter
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_shared_packets_proto_init() }
func file_shared_packets_proto_init() {
	if File_shared_packets_proto != nil {
		return
	}
	file_shared_packets_proto_msgTypes[0].OneofWrappers = []any{
		(*Packet_ErrorRes)(nil),
		(*Packet_LoginReq)(nil),
		(*Packet_LoginRes)(nil),
		(*Packet_RegisterReq)(nil),
		(*Packet_RegisterRes)(nil),
		(*Packet_MyCharactersListReq)(nil),
		(*Packet_MyCharactersListRes)(nil),
		(*Packet_CharacterJoinReq)(nil),
		(*Packet_CharacterJoinRes)(nil),
		(*Packet_CastSpellReq)(nil),
		(*Packet_CastSpellRes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_packets_proto_rawDesc), len(file_shared_packets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_packets_proto_goTypes,
		DependencyIndexes: file_shared_packets_proto_depIdxs,
		MessageInfos:      file_shared_packets_proto_msgTypes,
	}.Build()
	File_shared_packets_proto = out.File
	file_shared_packets_proto_goTypes = nil
	file_shared_packets_proto_depIdxs = nil
}
