// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: characters.sql

package sources

import (
	"context"
)

const getCharacterById = `-- name: GetCharacterById :one
SELECT id, account_id, nickname, level, xp, vitality, intelligence, willpower, dexterity, spirit, created_at FROM characters WHERE id = $1
`

func (q *Queries) GetCharacterById(ctx context.Context, id int32) (Character, error) {
	row := q.db.QueryRow(ctx, getCharacterById, id)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Nickname,
		&i.Level,
		&i.Xp,
		&i.Vitality,
		&i.Intelligence,
		&i.Willpower,
		&i.Dexterity,
		&i.Spirit,
		&i.CreatedAt,
	)
	return i, err
}

const getCharactersByAccountId = `-- name: GetCharactersByAccountId :many
SELECT id, account_id, nickname, level, xp, vitality, intelligence, willpower, dexterity, spirit, created_at FROM characters WHERE account_id = $1
`

func (q *Queries) GetCharactersByAccountId(ctx context.Context, accountID int32) ([]Character, error) {
	rows, err := q.db.Query(ctx, getCharactersByAccountId, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Nickname,
			&i.Level,
			&i.Xp,
			&i.Vitality,
			&i.Intelligence,
			&i.Willpower,
			&i.Dexterity,
			&i.Spirit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
