// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sources

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int32
	Username  string
	Password  string
	CreatedAt pgtype.Timestamptz
}
