// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sources

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int32
	Username  string
	Password  string
	CreatedAt pgtype.Timestamptz
}

type Character struct {
	ID           int32
	AccountID    int32
	Nickname     string
	Level        int32
	Xp           int32
	Vitality     int32
	Intelligence int32
	Willpower    int32
	Dexterity    int32
	Spirit       int32
	CreatedAt    pgtype.Timestamptz
}
